// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkkgcrknvpzelydttivp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRra2djcmtudnB6ZWx5ZHR0aXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjA3ODMsImV4cCI6MjA3MDk5Njc4M30.HikbTod_PiTXE55aq5uX-wsuBH7KPY5OD1a06k3Ups8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});